GET /mamcomtv/api/get_posts/?api_key=cda11Tlc9x7rRiJKh0dbpjSsFQoZg64VUnHMByCkvINe8E3wtG&page=1&count=200 HTTP/1.1 
Cache-Control: max-age=0 
Data-Agent: The Stream 
Host: themamcom.net 
Connection: Keep-Alive 
Accept-Encoding: gzip 
User-Agent: okhttp/3.10.0